name: Injection - Issue Title
on:
  issues:

env:
  FLAG: ${{ secrets.FLAG }}

permissions: {}

jobs:
  a:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.issue.title }}
    steps:
      - run: echo ${{ env.TITLE }}
